name: neuland
favicon: null
layout_spectrum: 0.19692
typography_spectrum: 0.98582
title: '#NEULAND'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#ffffff'
    - '#ff4242'
    - '#ffd9db'
    - '#ff6567'
  brandStrength: 0.6875
  lightness: 0.7372720625717193
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
